### ISSUE TITLE
App Crashes after back button pressed .

### ISSUE THREAD

**Issue by baselnassrallah** [telerik/telerik-xamarin-forms-samples#16]
hello , I implement this listview in my xamarin app , its works perfect but when i go back from this listview page the app crashes with this error :

System.NotSupportedException: 'Unable to activate instance of type Telerik.XamarinForms.DataControlsRenderer.Android.ListView.TemplateCellContainer from native handle 0x71 (key_handle 0x75b7bad).' 

please help me fix this issue .

I'm using visual studio 2019 community edition and
Telerik.Ui.For.Xamarin  version is 2019.2.513.1

**Comment by kerpecheva** [comment]
Hello, we haven't come across such an exception, so we would need more details on the concrete setup you have.  Could you please open a [support ticket](https://www.telerik.com/account/support-tickets) and send us at least the ListView definition with the used ItemTemplates and if possible, the referenced classes/view models?

Thanks in advance

**Comment by didiyordanova** [comment]
Hello @baselnassrallah 

Regarding to the System.NotSupportedException: 'Unable to activate instance of type Telerik.XamarinForms.DataControlsRenderer.Android.ListView.TemplateCellContainer, we have this issue logged in our feedback portal. You can check the item at the following link: https://feedback.telerik.com/xamarin/1410095-crash-when-upgrading-to-xamarin-forms-4-0 

Note that the feedback item status is Completed. A fix for it is included in the Telerik UI for Xamarin v **2019.2.603.360.**  Update the Telerik UI for Xamarin suite to this version or to a newer version.
