### ISSUE TITLE
Sample code for Telerik  ERP Demo app

### ISSUE THREAD

**Issue by ergodaveh** [telerik/telerik-xamarin-forms-samples#19]
Apps are available in both Android and iOS app stores, as such it seems to be a Xamarin Demo.   Is there any plan to include the Telerik ERP source code?

**Comment by GeorgeDarakchiev** [comment]
Hi @ergodaveh ,

We are currently working on providing the source code and you can check the [development](https://github.com/telerik/telerik-xamarin-forms-samples/tree/development/ERP) branch in case you want to look at the ERP source code. Please not that this is a work in progress and there will be further changes in this branch.

Regards,
Georgi

**Comment by didiyordanova** [comment]
Hi @ergodaveh,

You can find the source code of the Telerik ERP Demo app [here](https://github.com/telerik/telerik-xamarin-forms-samples/tree/master/ERP). In addition, we have introduced another two sample demo apps CRM and ToDo - for more details you can check the [Telerik UI for Xamarin Sample Apps](https://www.telerik.com/xamarin-ui/sample-apps) page.

Regards,
Didi
