### ISSUE TITLE
Sample is not building

### ISSUE THREAD

**Issue by kernshen** [telerik/telerik-xamarin-forms-samples#3]
QSF.Examples.TreeViewControl.CustomizationExample.ItemHierarchyAdapter
QSF.Examples.TreeViewControl.FirstLookExample.HierarchyAdapter

Above classes are inheriting an internal interface and they don't seem to be required?:

QSF.Examples.CalendarControl.MultiDayViewAppointmentsExample.AppointmentsGenerator

Appointment class doesn't contain the property RecurrenceRule.

**Comment by PavelRPavlov** [comment]
We are currently working on updating the code of this repo. We expect to fix all issue by the end of the day. Please pull the changes once available.

**Comment by PavelRPavlov** [comment]
Issues are fixed with https://github.com/telerik/telerik-xamarin-forms-samples/pull/5

**Comment by ramtechjoe** [comment]
Thanks
