### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MariaNabil** [telerik/telerik-xamarin-forms-samples#4]
Error 'IHierarchyAdapter' is inaccessible due to its protection level

**Comment by ramtechjoe** [comment]
Same here, please fix so samples can build and be reviewed

**Comment by PavelRPavlov** [comment]
We are currently working on updating the code of this repo. We expect to fix all issue by the end of the day. Please pull the changes once available.

**Comment by PavelRPavlov** [comment]
Issues are fixed with https://github.com/telerik/telerik-xamarin-forms-samples/pull/5
